"""Added readers table

Revision ID: 092e684af40f
Revises: 74d180f8b1c5
Create Date: 2023-04-14 00:00:11.674394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092e684af40f'
down_revision = '74d180f8b1c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'first_name', 'last_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    # ### end Alembic commands ###
