"""Rename pk column name of tables

Revision ID: 1aa33f2c776b
Revises: 29186ba5e003
Create Date: 2023-04-14 11:04:47.235311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa33f2c776b'
down_revision = '29186ba5e003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_books_publisher_id', table_name='books')
    op.create_unique_constraint(None, 'books', ['_id'])
    op.drop_constraint('books_publisher_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'id')
    op.drop_column('publisher', 'name')
    op.add_column('readers', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_constraint('readers_id_key', 'readers', type_='unique')
    op.drop_constraint('unique_id', 'readers', type_='unique')
    op.create_unique_constraint(None, 'readers', ['_id'])
    op.drop_column('readers', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'readers', type_='unique')
    op.create_unique_constraint('unique_id', 'readers', ['id'])
    op.create_unique_constraint('readers_id_key', 'readers', ['id'])
    op.drop_column('readers', '_id')
    op.add_column('publisher', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('books', sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_publisher_id_fkey', 'books', 'publisher', ['publisher_id'], ['_id'])
    op.drop_constraint(None, 'books', type_='unique')
    op.create_index('ix_books_publisher_id', 'books', ['publisher_id'], unique=False)
    op.drop_column('books', '_id')
    # ### end Alembic commands ###
