"""Dropped books foreign key with readers table

Revision ID: 29186ba5e003
Revises: 9d3c04020790
Create Date: 2023-04-14 10:53:10.712955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29186ba5e003'
down_revision = '9d3c04020790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_read_id', 'books', type_='foreignkey')
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_read_id', 'books', 'readers', ['reader_id'], ['id'])
    # ### end Alembic commands ###
