"""created readers_books table for many-to-many rs

Revision ID: 4a1e22bf7cbc
Revises: 1aa33f2c776b
Create Date: 2023-04-14 11:13:15.708756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1e22bf7cbc'
down_revision = '1aa33f2c776b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers_books',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books._id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_readers_books__id'), 'readers_books', ['_id'], unique=True)
    op.alter_column('readers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('readers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # op.drop_constraint('readers__id_key', 'readers', type_='unique')
    op.create_index(op.f('ix_readers__id'), 'readers', ['_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readers__id'), table_name='readers')
    op.create_unique_constraint('readers__id_key', 'readers', ['_id'])
    op.alter_column('readers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('readers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_readers_books__id'), table_name='readers_books')
    op.drop_table('readers_books')
    # ### end Alembic commands ###
