"""Added unique constraint for readers table

Revision ID: 61f66be548e3
Revises: 092e684af40f
Create Date: 2023-04-14 00:35:31.582602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f66be548e3'
down_revision = '092e684af40f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_id', 'readers', ['id'])
    op.create_unique_constraint(None, 'readers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readers', type_='unique')
    op.drop_constraint('unique_id', 'readers', type_='unique')
    # ### end Alembic commands ###
