"""Added foreign key to books table

Revision ID: 8802674aa8f5
Revises: 61f66be548e3
Create Date: 2023-04-14 00:35:59.810096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8802674aa8f5'
down_revision = '61f66be548e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_read_id', 'books', 'readers', ['reader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_read_id', 'books', type_='foreignkey')
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###
