"""Added fk for publisher in books table

Revision ID: 9d3c04020790
Revises: 01b07af1087e
Create Date: 2023-04-14 10:40:24.116905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3c04020790'
down_revision = '01b07af1087e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_publisher_id'), 'books', ['publisher_id'], unique=False)
    op.create_foreign_key(None, 'books', 'publisher', ['publisher_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_publisher_id'), table_name='books')
    op.drop_column('books', 'publisher_id')
    # ### end Alembic commands ###
